package com.example.system.mapper;

import com.example.system.entity.LocalFile;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface LocalFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_file
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_file
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    int insert(LocalFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_file
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    int insertSelective(LocalFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_file
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    LocalFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_file
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    int updateByPrimaryKeySelective(LocalFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_file
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    int updateByPrimaryKey(LocalFile record);


    /**
     * 查询所有文件
     * */
    List<LocalFile> selectAll();
}