package com.example.system.mapper;

import com.example.system.entity.SysQuestionnaireAnswer;
import com.example.system.entity.param.QuestionnaireAnswerParam;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface SysQuestionnaireAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_questionnaire_answer
     *
     * @mbg.generated Tue Nov 10 14:22:23 CST 2020
     */
    int insert(SysQuestionnaireAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_questionnaire_answer
     *
     * @mbg.generated Tue Nov 10 14:22:23 CST 2020
     */
    int insertSelective(SysQuestionnaireAnswer record);

    /**
     * 插入多条数据
     * */
    void insertAll(List<SysQuestionnaireAnswer> answerList);

    /**
     * 查询用户是否已经提交数据
     * */
    List<SysQuestionnaireAnswer> selectByQuestionnaireIdAndUserName(QuestionnaireAnswerParam param);
}