package com.example.system.mapper;

import com.example.system.entity.SysQuestionnaireAnswer;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface SysQuestionnaireAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_questionnaire_answer
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_questionnaire_answer
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    int insert(SysQuestionnaireAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_questionnaire_answer
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    int insertSelective(SysQuestionnaireAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_questionnaire_answer
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    SysQuestionnaireAnswer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_questionnaire_answer
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    int updateByPrimaryKeySelective(SysQuestionnaireAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_questionnaire_answer
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    int updateByPrimaryKey(SysQuestionnaireAnswer record);
}