package com.example.system.mapper;

import com.example.system.entity.SysQuestionnaire;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface SysQuestionnaireMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_questionnaire
     *
     * @mbg.generated Tue Nov 10 14:22:23 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_questionnaire
     *
     * @mbg.generated Tue Nov 10 14:22:23 CST 2020
     */
    int insert(SysQuestionnaire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_questionnaire
     *
     * @mbg.generated Tue Nov 10 14:22:23 CST 2020
     */
    int insertSelective(SysQuestionnaire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_questionnaire
     *
     * @mbg.generated Tue Nov 10 14:22:23 CST 2020
     */
    SysQuestionnaire selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_questionnaire
     *
     * @mbg.generated Tue Nov 10 14:22:23 CST 2020
     */
    int updateByPrimaryKeySelective(SysQuestionnaire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_questionnaire
     *
     * @mbg.generated Tue Nov 10 14:22:23 CST 2020
     */
    int updateByPrimaryKey(SysQuestionnaire record);
}