package com.example.system.mapper;

import com.example.system.entity.SysRole;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    int insertSelective(SysRole record);

    List<SysRole> selectByPrimaryKeys(List<String> roleIds);

    SysRole selectByRoleCode(String role);
}