package com.example.system.mapper;

import com.example.system.entity.SysSubject;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;
import java.util.List;

@Mapper
@Repository
public interface SysSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subject
     *
     * @mbg.generated Tue Nov 10 14:48:21 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subject
     *
     * @mbg.generated Tue Nov 10 14:48:21 CST 2020
     */
    int insert(SysSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subject
     *
     * @mbg.generated Tue Nov 10 14:48:21 CST 2020
     */
    int insertSelective(SysSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subject
     *
     * @mbg.generated Tue Nov 10 14:48:21 CST 2020
     */
    SysSubject selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subject
     *
     * @mbg.generated Tue Nov 10 14:48:21 CST 2020
     */
    int updateByPrimaryKeySelective(SysSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subject
     *
     * @mbg.generated Tue Nov 10 14:48:21 CST 2020
     */
    int updateByPrimaryKey(SysSubject record);

    /**
     * 根据ID列表查出 SysSubject
     * */
    List<SysSubject> selectByPrimaryKeys(List<String> ids);

    List<SysSubject> selectAll();
}