package com.example.questionnaire.mapper;

import com.example.questionnaire.entity.sysResOptionResult;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface sysResOptionResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res_option_result
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res_option_result
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    int insert(sysResOptionResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res_option_result
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    int insertSelective(sysResOptionResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res_option_result
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    sysResOptionResult selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res_option_result
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    int updateByPrimaryKeySelective(sysResOptionResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res_option_result
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    int updateByPrimaryKey(sysResOptionResult record);
}