package com.example.questionnaire.mapper;

import com.example.questionnaire.entity.SysResOption;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;
import java.util.List;

@Repository
@Mapper
public interface SysResOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res_option
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res_option
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    int insert(SysResOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res_option
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    int insertSelective(SysResOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res_option
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    SysResOption selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res_option
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    int updateByPrimaryKeySelective(SysResOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res_option
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    int updateByPrimaryKey(SysResOption record);

    List<SysResOption> selectAll();
}