package com.example.questionnaire.entity;

public class SysResOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_option.id
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_option.res_option_name
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    private String resOptionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_option.res_option_operation
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    private Integer resOptionOperation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_option.id
     *
     * @return the value of sys_res_option.id
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_option.id
     *
     * @param id the value for sys_res_option.id
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_option.res_option_name
     *
     * @return the value of sys_res_option.res_option_name
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public String getResOptionName() {
        return resOptionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_option.res_option_name
     *
     * @param resOptionName the value for sys_res_option.res_option_name
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public void setResOptionName(String resOptionName) {
        this.resOptionName = resOptionName == null ? null : resOptionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_option.res_option_operation
     *
     * @return the value of sys_res_option.res_option_operation
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public Integer getResOptionOperation() {
        return resOptionOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_option.res_option_operation
     *
     * @param resOptionOperation the value for sys_res_option.res_option_operation
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public void setResOptionOperation(Integer resOptionOperation) {
        this.resOptionOperation = resOptionOperation;
    }
}