package com.example.questionnaire.entity;

import java.util.Date;

public class SysResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_result.id
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_result.result_name
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    private String resultName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_result.status
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_result.created_at
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_result.update_at
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_result.id
     *
     * @return the value of sys_result.id
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_result.id
     *
     * @param id the value for sys_result.id
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_result.result_name
     *
     * @return the value of sys_result.result_name
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public String getResultName() {
        return resultName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_result.result_name
     *
     * @param resultName the value for sys_result.result_name
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public void setResultName(String resultName) {
        this.resultName = resultName == null ? null : resultName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_result.status
     *
     * @return the value of sys_result.status
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_result.status
     *
     * @param status the value for sys_result.status
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_result.created_at
     *
     * @return the value of sys_result.created_at
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_result.created_at
     *
     * @param createdAt the value for sys_result.created_at
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_result.update_at
     *
     * @return the value of sys_result.update_at
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_result.update_at
     *
     * @param updateAt the value for sys_result.update_at
     *
     * @mbg.generated Mon Nov 23 16:36:26 CST 2020
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}