package com.example.system.entity;

import java.util.Date;

public class LocalFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_file.id
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_file.file_name
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_file.url
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_file.create_by
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_file.create_time
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_file.update_time
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_file.id
     *
     * @return the value of local_file.id
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_file.id
     *
     * @param id the value for local_file.id
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_file.file_name
     *
     * @return the value of local_file.file_name
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_file.file_name
     *
     * @param fileName the value for local_file.file_name
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_file.url
     *
     * @return the value of local_file.url
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_file.url
     *
     * @param url the value for local_file.url
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_file.create_by
     *
     * @return the value of local_file.create_by
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_file.create_by
     *
     * @param createBy the value for local_file.create_by
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_file.create_time
     *
     * @return the value of local_file.create_time
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_file.create_time
     *
     * @param createTime the value for local_file.create_time
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_file.update_time
     *
     * @return the value of local_file.update_time
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_file.update_time
     *
     * @param updateTime the value for local_file.update_time
     *
     * @mbg.generated Mon Nov 09 17:13:50 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}