package com.example.system.entity;

import java.util.Date;

public class SysQuestionnaire {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_questionnaire.id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_questionnaire.questnnaire_name
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    private String questnnaireName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_questionnaire.status
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_questionnaire.created_at
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_questionnaire.update_at
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_questionnaire.id
     *
     * @return the value of sys_questionnaire.id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_questionnaire.id
     *
     * @param id the value for sys_questionnaire.id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_questionnaire.questnnaire_name
     *
     * @return the value of sys_questionnaire.questnnaire_name
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public String getQuestnnaireName() {
        return questnnaireName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_questionnaire.questnnaire_name
     *
     * @param questnnaireName the value for sys_questionnaire.questnnaire_name
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public void setQuestnnaireName(String questnnaireName) {
        this.questnnaireName = questnnaireName == null ? null : questnnaireName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_questionnaire.status
     *
     * @return the value of sys_questionnaire.status
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_questionnaire.status
     *
     * @param status the value for sys_questionnaire.status
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_questionnaire.created_at
     *
     * @return the value of sys_questionnaire.created_at
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_questionnaire.created_at
     *
     * @param createdAt the value for sys_questionnaire.created_at
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_questionnaire.update_at
     *
     * @return the value of sys_questionnaire.update_at
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_questionnaire.update_at
     *
     * @param updateAt the value for sys_questionnaire.update_at
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}