package com.example.system.entity;

public class SysQuestionnaireAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_questionnaire_answer.id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_questionnaire_answer.subject_id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    private String subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_questionnaire_answer.questionnaire_id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    private String questionnaireId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_questionnaire_answer.user_id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_questionnaire_answer.answer
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_questionnaire_answer.id
     *
     * @return the value of sys_questionnaire_answer.id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_questionnaire_answer.id
     *
     * @param id the value for sys_questionnaire_answer.id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_questionnaire_answer.subject_id
     *
     * @return the value of sys_questionnaire_answer.subject_id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_questionnaire_answer.subject_id
     *
     * @param subjectId the value for sys_questionnaire_answer.subject_id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId == null ? null : subjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_questionnaire_answer.questionnaire_id
     *
     * @return the value of sys_questionnaire_answer.questionnaire_id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public String getQuestionnaireId() {
        return questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_questionnaire_answer.questionnaire_id
     *
     * @param questionnaireId the value for sys_questionnaire_answer.questionnaire_id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public void setQuestionnaireId(String questionnaireId) {
        this.questionnaireId = questionnaireId == null ? null : questionnaireId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_questionnaire_answer.user_id
     *
     * @return the value of sys_questionnaire_answer.user_id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_questionnaire_answer.user_id
     *
     * @param userId the value for sys_questionnaire_answer.user_id
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_questionnaire_answer.answer
     *
     * @return the value of sys_questionnaire_answer.answer
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_questionnaire_answer.answer
     *
     * @param answer the value for sys_questionnaire_answer.answer
     *
     * @mbg.generated Tue Nov 10 11:29:05 CST 2020
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}