package com.example.system.entity;

public class SysQuestionnaireSubject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_questionnaire_subject.id
     *
     * @mbg.generated Tue Nov 10 11:52:51 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_questionnaire_subject.questionnaire_id
     *
     * @mbg.generated Tue Nov 10 11:52:51 CST 2020
     */
    private String questionnaireId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_questionnaire_subject.subject_id
     *
     * @mbg.generated Tue Nov 10 11:52:51 CST 2020
     */
    private String subjectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_questionnaire_subject.id
     *
     * @return the value of sys_questionnaire_subject.id
     *
     * @mbg.generated Tue Nov 10 11:52:51 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_questionnaire_subject.id
     *
     * @param id the value for sys_questionnaire_subject.id
     *
     * @mbg.generated Tue Nov 10 11:52:51 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_questionnaire_subject.questionnaire_id
     *
     * @return the value of sys_questionnaire_subject.questionnaire_id
     *
     * @mbg.generated Tue Nov 10 11:52:51 CST 2020
     */
    public String getQuestionnaireId() {
        return questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_questionnaire_subject.questionnaire_id
     *
     * @param questionnaireId the value for sys_questionnaire_subject.questionnaire_id
     *
     * @mbg.generated Tue Nov 10 11:52:51 CST 2020
     */
    public void setQuestionnaireId(String questionnaireId) {
        this.questionnaireId = questionnaireId == null ? null : questionnaireId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_questionnaire_subject.subject_id
     *
     * @return the value of sys_questionnaire_subject.subject_id
     *
     * @mbg.generated Tue Nov 10 11:52:51 CST 2020
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_questionnaire_subject.subject_id
     *
     * @param subjectId the value for sys_questionnaire_subject.subject_id
     *
     * @mbg.generated Tue Nov 10 11:52:51 CST 2020
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId == null ? null : subjectId.trim();
    }
}